In [25]:
import cv2
import math

img = cv2.imread("screenshot.png")

img_shape = img.shape
tile_size = (83.3, 83.3)
offset = (83.3, 83.3)

for i in range(9):
    for j in range(9):
        cropped_img = img[int(offset[1]*i):int(min(offset[1]*i+tile_size[1], img_shape[0])), int(offset[0]*j):int(min(offset[0]*j+tile_size[0], img_shape[1]))]
        # Debugging the tiles
        cropped_img = cropped_img[10:75, 10:75]
        cv2.imwrite("debug_" + str(i) + "_" + str(j) + ".png", cropped_img)

In [31]:
import os
import re
digits = np.zeros((9,9), dtype=int)
for i in range(9):
    for j in range(9):
        # Run tesseract on images, using a page segmentation mode (psm) to treat every image as a single char.
        command = f"tesseract debug_{i}_{j}.png test --psm 10 && cat test.txt"
        os.system(command)
        with open("test.txt") as f:
            lines = f.readlines()
            if (re.match(r'\d', lines[0])):
                digits[i][j] = int(lines[0][0])
            else:
                digits[i][j] = 0
print(digits)       


[[5 3 0 0 7 0 0 0 0]
 [6 0 0 1 9 5 0 0 0]
 [0 9 8 0 0 0 0 6 0]
 [8 0 0 0 6 0 0 0 3]
 [4 0 0 8 0 3 0 0 1]
 [7 0 0 0 2 0 0 0 6]
 [0 6 0 0 0 0 2 8 0]
 [0 0 0 4 1 9 0 0 5]
 [0 0 0 0 8 0 0 7 9]]


In [32]:
with open("output_puzzle.txt", "a") as f:
    for i in range(9):
        for j in range(9):
            f.write(str(digits[i][j])+" ")
        f.write("\n")